Repository volcano-sh/volcano-global, pull requests merged in 2025-01, with the labels that each got.

#9 chore: remove the pod group
  cmd/controller-manager/main.go
  docs/deploy/README.md
  docs/deploy/exmaple/mindspore-cpu.yaml
  pkg/controllers/deployment/deployment_controller.go
  pkg/controllers/deployment/deployment_controller_handlers.go
  pkg/controllers/deployment/utils.go
  pkg/dispatcher/api/resource_binding_info.go
  pkg/dispatcher/cache/cache.go
  pkg/dispatcher/cache/event_handlers.go
  pkg/dispatcher/cache/obj_converters.go
  pkg/dispatcher/cache/resource_binding_processor.go
  pkg/dispatcher/cache/snapshot.go
  pkg/dispatcher/dispatcher.go
  pkg/webhooks/resourcebinding/mutating/mutating.go
  pkg/workload/interface.go
  pkg/workload/volcanojob.go
  pkg/workload/workload.go
Labels: size/XL, lgtm, approved

#8 Update desgin img
  README.md
  docs/imgs/volcano_global_design.drawio
  docs/imgs/volcano_global_design.png
  docs/imgs/volcano_global_design.svg
Labels: lgtm, approved, size/L

#10 Bump karmada version to support resourceBinding suspension.
  .gitignore
  Makefile
  README.md
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  docs/deploy/README.md
  docs/deploy/exmaple/mindspore-cpu.yaml
  docs/deploy/queue-resource-interpreter-customization.yaml
  docs/deploy/volcano-global-all-queue-propagation.yaml
  docs/deploy/volcano-global-controller-manager.yaml
  docs/imgs/architecture_diagram.drawio
  docs/imgs/architecture_diagram.svg
  go.mod
  go.sum
  pkg/dispatcher/cache/cache.go
  pkg/dispatcher/cache/event_handlers.go
  pkg/dispatcher/cache/resource_binding_processor.go
  pkg/dispatcher/cache/utils/utils.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/options/options.go
  pkg/utils/queue.go
  pkg/utils/utils.go
  pkg/webhooks/resourcebinding/mutating/mutating.go
  pkg/webhooks/resourcebinding/mutating/mutating_test.go
  pkg/workload/deployment.go
  pkg/workload/interface.go
  pkg/workload/volcanojob.go
  pkg/workload/workload.go
Labels: size/XXL, lgtm, approved

#6 Change the traversal method of queue to round-robin
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/dispatcher/uthelper/mock_cache.go
Labels: lgtm, approved, size/L
